[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "{{project-description}}"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"

